### PR TITLE
Feat/post topic creation

### LINKED ISSUE #2: Allow requests to be posted to create a new topic
Also store the content of the referrer header with the request and return it when fetching the message.

### PR DESCRIPTION
**Pull request by rmw2**
resolves #2 

Allow `POST /topic/:id` to create a new topic, previously only possible with `GET`.  Also add some documentation and extract SQL query strings to a separate file for better management.

This doesn't do anything to save referrer headers with the topic, but I can add that as an extra field in the topic JSON without changing any queries if we want it.

### CODE REVIEW

**Comment by rmw2** [comment]
Update: found this spec here: https://github.com/uport-project/specs/blob/develop/rest-apis/request-server.md

Will fix this to match

**Comment by rmw2** [comment]
Ok, now implements the POST-to-create-topic flow, returning the topic URL in the Location header as described [here](https://github.com/uport-project/specs/blob/develop/rest-apis/request-server.md).

The structure of the object expected by the `doHandler` callback has changed slightly to accommodate non-error request codes other than 200, and headers that may be set inside a particular handler.

The `referrerUrl` described in that document is not implemented in this PR, but I think that is a separate feature.

**Comment by rmw2** [comment]
Good catch! Though I'm a little confused as it's currently the same in `master`, that is it refers to `topic_create` in serverless.yml, but the filename and module export is called `topic_post` -- do you know what's up with that?

**Comment by c-castillo** [comment]
@rmw2 It is probably a copy-paste error. It is better to follow the same name conventions across the entire project. Might need a fix

**Pull request merged**
